# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(default='static/img/default.png', upload_to='static/img/headers/', verbose_name='用户头像'),
        ),
    ]
